export const MONTHS = [
  'Janeiro',
  'Fevereiro',
  'Março',
  'Abril',
  'Maio',
  'Junho',
  'Julho',
  'Agosto',
  'Setembro',
  'Outubro',
  'Novembro',
  'Dezembro',
]

export const CAT_COLORS: Record<string, string> = {
  Moradia: '#2563eb',
  Transporte: '#3b82f6',
  Alimentação: '#16a34a',
  Saúde: '#f97316',
  Lazer: '#6366f1',
  Financeiro: '#0ea5e9',
  Outros: '#9ca3af',
}

export const CAT_KW: Record<string, string[]> = {
  Moradia: [
    'água',
    'luz',
    'gás',
    'aluguel',
    'condomínio',
    'iptu',
    'energia',
    'enel',
    'sabesp',
    'copel',
    'cemig',
    'comgás',
  ],
  Transporte: [
    'uber',
    '99',
    'combustível',
    'gasolina',
    'estacionamento',
    'pedágio',
    'ipva',
    'detran',
    'carro',
    'moto',
    'ônibus',
    'metrô',
  ],
  Alimentação: [
    'supermercado',
    'mercado',
    'ifood',
    'rappi',
    'restaurante',
    'lanchonete',
    'padaria',
    'açougue',
    'comida',
    'refeição',
    'extra',
    'carrefour',
    'atacadão',
  ],
  Saúde: [
    'farmácia',
    'drogaria',
    'plano de saúde',
    'consulta',
    'médico',
    'hospital',
    'unimed',
    'amil',
    'hapvida',
  ],
  Lazer: [
    'netflix',
    'spotify',
    'amazon',
    'disney',
    'hbo',
    'streaming',
    'cinema',
    'teatro',
    'viagem',
    'hotel',
    'airbnb',
    'game',
  ],
  Financeiro: [
    'inter',
    'nubank',
    'caixa',
    'bradesco',
    'itaú',
    'santander',
    'banco',
    'fatura',
    'cartão',
    'empréstimo',
    'mercadopago',
    'picpay',
    'pix',
  ],
}

/** Categorias sugeridas na UI de importação de extrato (subset fixo). */
export const IMPORT_CATEGORY_OPTIONS = [
  'Moradia',
  'Transporte',
  'Alimentação',
  'Saúde',
  'Lazer',
  'Financeiro',
  'Outros',
] as const
